---
title: "stepwise in cox"
author: "Tian He"
date: "Monday, May 04, 2015"
output: html_document
---
```{r setup}
setwd("C:/Users/Tian/Desktop/459 Final/R")
brc <- read.csv("C:/Users/Tian/Desktop/459 Final/R/brc.csv")

attach(brc)
```

```{r split}
set.seed(459)
test.rows <- sample(1:nrow(brc), size=82, replace=FALSE)
train <- brc[-test.rows,]
test <- brc[test.rows,]

summary(train)
summary(test)

dim(train)
dim(test)

```

```{r pre-selection}
detach(brc)
attach(train)

library(survival)

status <- as.factor(vital_status)
surv <-Surv(time, status=="Dead")

getwd()
N <- colnames(train)
N
sink(file="expr.txt")

for(i in 27:170) {
    cfit <- try(coxph(surv ~ train[,i]),silent=T) 
  if(class(cfit) == "coxph"){
   expr <- list(name=N[i],cfit=cfit)
   print(expr)}
  
}
sink(NULL)



getwd()
N <- colnames(train)
N
sink(file="cli.txt")

for(i in 3:26) {
    cfit <- try(coxph(surv ~ train[,i]),silent=T) 
  if(class(cfit) == "coxph"){
   clin <- list(name=N[i],cfit=cfit)
   print(clin)}
  
}
sink(NULL)
```


```{r stepwise1}
attach(train)

library(survival)

status <- as.factor(vital_status)
surv1 <-Surv(time, status=="Dead")

cfit1 <- coxph(surv1 ~ X14.3.3_epsilon + alpha.Catenin + Bax + Beclin + C.Raf + Caveolin.1 + Chk2_pT68 + Claudin.7 + Collagen_VI + Cyclin_B1 + Dvl3 + FOXO3a + GSK3.alpha.beta_pS21_S9 + Lck + NF.kB.p65_pS536 + P.Cadherin + p27_pT157 + p38_MAPK + Paxillin + Pea.15 + PI3K.p110.alpha + Rb_pS807_S811 + STAT3_pY705 + Tuberin + SCD1 + ASNS, data=train)
summary(cfit1)

step(cfit1)

### C index 1

detach(train)
attach(test)


status <- as.factor(vital_status)
surv2 <- Surv(time, status=="Dead")

cfit2 <- coxph(surv2 ~ P.Cadherin + NF.kB.p65_pS536 + p27_pT157 + Paxillin + PI3K.p110.alpha, data = test)


summary(cfit2)

library(rms)
dd <- datadist(NF.kB.p65_pS536, P.Cadherin, p27_pT157, Paxillin, PI3K.p110.alpha)
options(datadist="test")

m2 <- cph(surv2 ~ NF.kB.p65_pS536 + P.Cadherin + p27_pT157 + Paxillin + PI3K.p110.alpha, x=TRUE, y=TRUE, data = test)
m2

detach(test)
```

```{r stepwise2}
attach(train)

status <- as.factor(vital_status)
surv3 <-Surv(time, status=="Dead")

cfit3 <- coxph(surv3 ~ patient_consent_status + age_at_diagnosis + ajcc_nodes_pathologic_pn + ajcc_metastasis_pathologic_pm + er_status_by_ihc + icd_o_3_site, data=train)
summary(cfit3)

step(cfit3)

### C index 2
detach(train)
attach(test)

library(survival)
status <- as.factor(vital_status)
surv4 <- Surv(time,status=="Dead")

cfit4 <- coxph(surv4 ~ patient_consent_status + age_at_diagnosis + ajcc_metastasis_pathologic_pm + er_status_by_ihc, data = test)
summary(cfit4)

dd <- datadist(patient_consent_status, age_at_diagnosis, ajcc_metastasis_pathologic_pm, er_status_by_ihc)
options(datadist="test")

m4 <- cph(surv4 ~ patient_consent_status + age_at_diagnosis + ajcc_metastasis_pathologic_pm + er_status_by_ihc, x=TRUE, y=TRUE, data = test)
m4
```

```{r combine}
detach(test)
attach(train)

status <- vital_status
surv5 <- Surv(time, status=="Dead")

cfit5 <- coxph(surv5 ~ X14.3.3_epsilon + alpha.Catenin + Bax + Beclin + C.Raf + Caveolin.1 + Chk2_pT68 + Claudin.7 + Collagen_VI + Cyclin_B1 + Dvl3 + FOXO3a + GSK3.alpha.beta_pS21_S9 + Lck + NF.kB.p65_pS536 + P.Cadherin + p27_pT157 + p38_MAPK + Paxillin + Pea.15 + PI3K.p110.alpha + Rb_pS807_S811 + STAT3_pY705 + Tuberin + SCD1 + ASNS + patient_consent_status + age_at_diagnosis + ajcc_nodes_pathologic_pn + ajcc_metastasis_pathologic_pm + er_status_by_ihc + icd_o_3_site, data=train)
summary(cfit5)

step(cfit5)

### C index 3
detach(train)
attach(test)

status <- vital_status
surv6 <- Surv(time, status=="Dead")

cfit6 <- coxph(surv6 ~ X14.3.3_epsilon + alpha.Catenin + Bax + Beclin + C.Raf + Caveolin.1 + Chk2_pT68 + Claudin.7 + Collagen_VI + Cyclin_B1 + Dvl3 + FOXO3a + GSK3.alpha.beta_pS21_S9 + Lck + NF.kB.p65_pS536 + P.Cadherin + p27_pT157 + p38_MAPK + Paxillin + Pea.15 + PI3K.p110.alpha + Rb_pS807_S811 + STAT3_pY705 + Tuberin + SCD1 + ASNS + age_at_diagnosis + ajcc_metastasis_pathologic_pm + er_status_by_ihc, data = test)
summary(cfit6)

m6 <- cph(surv6 ~ X14.3.3_epsilon + alpha.Catenin + Bax + Beclin + C.Raf + Caveolin.1 + Chk2_pT68 + Claudin.7 + Collagen_VI + Cyclin_B1 + Dvl3 + FOXO3a + GSK3.alpha.beta_pS21_S9 + Lck + NF.kB.p65_pS536 + P.Cadherin + p27_pT157 + p38_MAPK + Paxillin + Pea.15 + PI3K.p110.alpha + Rb_pS807_S811 + STAT3_pY705 + Tuberin + SCD1 + ASNS + age_at_diagnosis + ajcc_metastasis_pathologic_pm + er_status_by_ihc, data = test)
m6
```

```{r finish}
detach(test)
```